name: Test

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Build variant to test'
        default: 'treble_arm64_bgN'
        required: false
        type: string

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -f build/Dockerfile -t ponces/treble .

      - name: Get Keys
        uses: actions/checkout@v4
        with:
          repository: ponces/vendor_ponces-priv
          token: ${{ secrets.GH_TOKEN }}
          path: vendor_ponces-priv

      - name: Build ROM
        run: |
          mkdir builds
          docker run --rm \
                     --privileged \
                     --name test \
                     --volume ${{ github.workspace }}/builds:/root/builds \
                     --volume ${{ github.workspace }}/vendor_ponces-priv:/aosp/vendor/ponces-priv \
                     ponces/treble treblebuild ${{ inputs.variant }}

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.variant }}
          path: builds/*.xz

  cleanup:
    needs: build
    runs-on: self-hosted
    if: ${{ always() }}
    steps:
      - name: Cleanup
        run: docker stop test || true
